import i10E1Cxye00ITuB from "../../assets/images/i10E1Cxye00ITuB.webp";
import i1TnWn1dH1xKlEc from "../../assets/images/i1TnWn1dH1xKlEc.webp";
import i1Tur9QW4EPtY from "../../assets/images/i1Tur9QW4EPtY.webp";
import i1UzYuGghfP1cO from "../../assets/images/i1UzYuGghfP1cO.webp";

const AerodynamicsSettings = () => (
  <>
    <div className="manual_detail">
      <div className="content_header">
        <h1>Aerodynamics / 空气动力学</h1>
      </div>
      <div className="body">
        <h3 className="section-header">
          ● Downforce / ● 下压力
        </h3>

        <h3>
          Improving High-Speed Performance / 决定高速性能的关键
        </h3>

        <div className="bilingual">
          <p lang="en">
            At high speeds, aerodynamic effects become a major factor. These can broadly be divided into two areas: drag, which limits top speed, and lift, which reduces tire load by acting to raise the car. The two are closely related, as changes that reduce drag can also increase lift, while measures that reduce lift often add drag. Achieving the right balance between them is essential.
            <br />
            <br />
            A key aspect of high-speed tuning is the management of downforce. Downforce is generated by aerodynamic components that create pressure differences, pushing the car toward the road and increasing tire load. While increased downforce improves stability and cornering performance—particularly in high-speed turns—it also adds drag and can reduce top speed. Conversely, reducing downforce lowers drag and increases straight-line speed, but at the expense of cornering grip and stability.
            <br />
            <br />
            The required level of downforce depends on the nature of the circuit. Although it may seem beneficial to run high downforce from the outset, this does not always produce the best results. A common approach is to begin with relatively low downforce and increase it gradually based on the demands of high-speed corners. For low-power cars, prioritizing straight-line speed by limiting excess downforce can often be more effective.
            <br />
            <br />
            Adjusting the balance of front and rear downforce also influences handling at high speed. Increasing front downforce raises front grip and tends to reduce understeer, promoting a more responsive turn-in, while increasing rear downforce improves rear stability and tends to reduce oversteer. Fine adjustments of aerodynamic balance can have a significant impact on performance, particularly on high-speed circuits.
          </p>
          <p lang="zh">
            高速下空气影响分两类：限制极速的阻力，与试图抬起车辆的升力；二者往往此消彼长，需按设定找平衡。实务上常转化为下压力问题——通过前唇、尾翼等把车身压向地面，提高高速稳定与弯速，但要兼顾前后平衡与阻力代价。
          </p>
        </div>

        <p className="image">
          <img alt="" src={i1Tur9QW4EPtY} />
        </p>

        <p className="image">
          <img alt="" src={i10E1Cxye00ITuB} />
        </p>

        <p className="image">
          <img alt="" src={i1UzYuGghfP1cO} />
        </p>

        <p className="image">
          <img alt="" src={i1TnWn1dH1xKlEc} />
        </p>
      </div>
    </div>
  </>
);

export default AerodynamicsSettings;
