import i10E1Cxye00ITuB from "../../assets/images/i10E1Cxye00ITuB.webp";
import i1TnWn1dH1xKlEc from "../../assets/images/i1TnWn1dH1xKlEc.webp";
import i1Tur9QW4EPtY from "../../assets/images/i1Tur9QW4EPtY.webp";
import i1UzYuGghfP1cO from "../../assets/images/i1UzYuGghfP1cO.webp";

const AerodynamicsSettings = () => (
  <>
    <div className="manual_detail">
      <div className="content_header">
        <h1 className="bilingual-title"><span lang="en">Aerodynamics</span><span className="bilingual-sep"> / </span><span lang="zh">空气动力学</span></h1>
      </div>
      <div className="body">
        <h3 className="section-header bilingual-title"><span lang="en">● Downforce</span><span className="bilingual-sep"> / </span><span lang="zh">● 下压力</span></h3>

        <h3 className="bilingual-title"><span lang="en">Improving High-Speed Performance</span><span className="bilingual-sep"> / </span><span lang="zh">决定高速行驶性能的关键</span></h3>

        <div className="bilingual">
          <p lang="en">
            At high speeds, aerodynamic effects become a major factor. These can broadly be divided into two areas: drag, which limits top speed, and lift, which reduces tire load by acting to raise the car. The two are closely related, as changes that reduce drag can also increase lift, while measures that reduce lift often add drag. Achieving the right balance between them is essential.
          </p>
          <p lang="zh">
            高速行驶时空气的存在不可忽视，大致分为两类影响：一是成为最高速度之墙的空气阻力，二是试图托起车辆的升力。二者处于「减阻则升力增、减升力则阻力增」的相反关系，须靠设定取得最佳平衡。
          </p>
        </div>

        <div className="bilingual">
          <p lang="en">
            A key aspect of high-speed tuning is the management of downforce. Downforce is generated by aerodynamic components that create pressure differences, pushing the car toward the road and increasing tire load. While increased downforce improves stability and cornering performance—particularly in high-speed turns—it also adds drag and can reduce top speed. Conversely, reducing downforce lowers drag and increases straight-line speed, but at the expense of cornering grip and stability.
          </p>
          <p lang="zh">
            实际设定中，这可改写成下压力问题。下压力是把空气阻力之力作为把车压向路面的力来利用：加强下压力则最高速度下降，但过弯时车辆更稳，尤其能提高高速弯旋回速度；减弱下压力则弯速下降，但可延伸直道最高速度。
          </p>
        </div>

        <div className="bilingual">
          <p lang="en">
            The required level of downforce depends on the nature of the circuit. Although it may seem beneficial to run high downforce from the outset, this does not always produce the best results. A common approach is to begin with relatively low downforce and increase it gradually based on the demands of high-speed corners. For low-power cars, prioritizing straight-line speed by limiting excess downforce can often be more effective.
          </p>
          <p lang="zh">
            下压力大小由行驶舞台决定，但从一开始就加强下压力的设定不会有好结果。应以必要最小下压力做设定，再按高速弯等重要性逐渐加强。小排量车则宁可把下压力归零、重视极速更好。
          </p>
        </div>

        <div className="bilingual">
          <p lang="en">
            Adjusting the balance of front and rear downforce also influences handling at high speed. Increasing front downforce raises front grip and tends to reduce understeer, promoting a more responsive turn-in, while increasing rear downforce improves rear stability and tends to reduce oversteer. Fine adjustments of aerodynamic balance can have a significant impact on performance, particularly on high-speed circuits.
          </p>
          <p lang="zh">
            另一方面，前后分别调整下压力，也可用来改变高速弯的操控特性：加强前部则前轮抓地提高、倾向转向过度；加强后部则相反、倾向转向不足。在高速赛道是效果很大的调校。
          </p>
        </div>

        <p className="image">
          <img alt="" src={i1Tur9QW4EPtY} />
        </p>

        <p className="image">
          <img alt="" src={i10E1Cxye00ITuB} />
        </p>

        <p className="image">
          <img alt="" src={i1UzYuGghfP1cO} />
        </p>

        <p className="image">
          <img alt="" src={i1TnWn1dH1xKlEc} />
        </p>
      </div>
    </div>
  </>
);

export default AerodynamicsSettings;
