import i16xDdiIScrECTH from "../../assets/images/i16xDdiIScrECTH.webp";
import i1Cf1luD0oa5scc from "../../assets/images/i1Cf1luD0oa5scc.webp";
import i1PE93sKsGeGNb from "../../assets/images/i1PE93sKsGeGNb.webp";
import i1UoGnYMFM90Sz from "../../assets/images/i1UoGnYMFM90Sz.webp";
import i1W6VS3qRqQcxuB from "../../assets/images/i1W6VS3qRqQcxuB.webp";

const AerodynamicTuning = () => (
  <>
    <div className="manual_detail">
      <div className="content_header">
        <h1>Aerodynamic Tuning / 空气动力学调校</h1>
      </div>
      <div className="body">
        <div className="bilingual">
          <p lang="en">
            Aerodynamic parts are often added for styling, but when used correctly they play an important role in optimizing performance. Well-designed aerodynamics can reduce drag and control lift, improving high-speed stability. The downforce generated by these components increases tire load and helps maximize grip and controllability. However, aerodynamic tuning must be balanced with the suspension and overall vehicle setup, as poor implementation can reduce performance.
          </p>
          <p lang="zh">
            空力套件常出于外观，但在认真改装中很重要：高速下降低阻力与升力，提升性能；下压力尤其能提高稳定性并挖掘轮胎抓地，是操控调校不可或缺的一环。
          </p>
        </div>

        <h3>
          Front Spoiler / 前扰流板
        </h3>

        <div className="bilingual">
          <p lang="en">
            These components are designed to control airflow beneath the car and reduce lift. However, if poorly designed or improperly installed, they can disrupt airflow and increase pressure under the body, reducing stability. In extreme cases, this can lead to a significant loss of control.
          </p>
          <p lang="zh">
            抑制车底进气、降低升力；但若件形不佳且车高过低，气流在底板堆积反而产生前端升力，最坏可失控。需善用车顶来流。
          </p>
        </div>

        <p className="image">
          <img alt="" src={i16xDdiIScrECTH} />
        </p>

        <h3>
          Rear Bumper Spoiler / 后保险杠扰流
        </h3>

        <div className="bilingual">
          <p lang="en">
            These components are designed to shape airflow around the rear bumper, helping to reduce turbulence and improve overall aerodynamic efficiency. They can be integrated into the bumper as a single unit or added as a separate attachment beneath it. The integrated type is often referred to as a rear bumper spoiler, while the add-on type is commonly called a rear under spoiler or rear skirt.
          </p>
          <p lang="zh">
            优化后杠周围气流、抑制尾部涡流；与后杠一体称后杠扰流，装在下部常称后下扰流或侧裙后段等。
          </p>
        </div>

        <p className="image">
          <img alt="" src={i1PE93sKsGeGNb} />
        </p>

        <h3>
          Side Spoiler / 侧裙
        </h3>

        <div className="bilingual">
          <p lang="en">
            Also known as side skirts or side steps, these are mounted along the side sills of the body. They help manage airflow along the sides of the car and can reduce turbulence.
          </p>
          <p lang="zh">
            亦称侧裙/侧踏板，装于侧 sill，减少车身侧面扰流。
          </p>
        </div>

        <p className="image">
          <img alt="" src={i1UoGnYMFM90Sz} />
        </p>

        <h3>
          Rear Wing / 尾翼
        </h3>

        <div className="bilingual">
          <p lang="en">
            Mounted on the upper rear of the body, rear wings help manage airflow and generate downforce. Their shape is designed to reduce lift and improve high-speed stability. Larger wings can produce greater downforce, increasing load on the rear tires and improving grip, although this is often accompanied by increased drag.
          </p>
          <p lang="zh">
            装于车身后部上方，整流并抑制尾涡；反翼型可产生下压力，尺寸越大下压力越强，有利于后轮抓地。
          </p>
        </div>

        <p className="image">
          <img alt="" src={i1Cf1luD0oa5scc} />
        </p>

        <h3>
          Rear Diffuser / 尾部扩散器
        </h3>

        <div className="bilingual">
          <p lang="en">
            Rear diffusers are fitted beneath the rear of the car and work by accelerating airflow from the underbody, helping to lower pressure and generate downforce. They are widely used in racing applications, and their effectiveness depends on factors such as ride height and overall underbody airflow.
          </p>
          <p lang="zh">
            加速车底气流自后杠下方排出以产生负压、获得下压力；赛车常见，底板与路面间隙越小效果越大。
          </p>
        </div>

        <p className="image">
          <img alt="" src={i1W6VS3qRqQcxuB} />
        </p>
      </div>
    </div>
  </>
);

export default AerodynamicTuning;
