import i16xDdiIScrECTH from "../../assets/images/i16xDdiIScrECTH.webp";
import i1Cf1luD0oa5scc from "../../assets/images/i1Cf1luD0oa5scc.webp";
import i1PE93sKsGeGNb from "../../assets/images/i1PE93sKsGeGNb.webp";
import i1UoGnYMFM90Sz from "../../assets/images/i1UoGnYMFM90Sz.webp";
import i1W6VS3qRqQcxuB from "../../assets/images/i1W6VS3qRqQcxuB.webp";

const AerodynamicTuning = () => (
  <>
    <div className="manual_detail">
      <div className="content_header">
        <h1 className="bilingual-title"><span lang="en">Aerodynamic Tuning</span><span className="bilingual-sep"> / </span><span lang="zh">空气动力学调校</span></h1>
      </div>
      <div className="body">
        <div className="bilingual">
          <p lang="en">
            Aerodynamic parts are often added for styling, but when used correctly they play an important role in optimizing performance. Well-designed aerodynamics can reduce drag and control lift, improving high-speed stability. The downforce generated by these components increases tire load and helps maximize grip and controllability. However, aerodynamic tuning must be balanced with the suspension and overall vehicle setup, as poor implementation can reduce performance.
          </p>
          <p lang="zh">
            一般多为外观而装的空力套件，在正式调校车上也发挥着非常重要的功能。主要目的是降低高速区使车速难以上升的空气阻力，以及试图托起车身的升力，从而提高行驶性能。尤其由空力件产生的把车体向下压的力（下压力），对提高姿态稳定并拉出轮胎抓地不可或缺，对操控性提升贡献很大。但空力调校须与含悬架在内的整体取得平衡；不恰当的调校反而恶化行驶性能也不罕见。
          </p>
        </div>

        <h3 className="bilingual-title"><span lang="en">Front Spoiler</span><span className="bilingual-sep"> / </span><span lang="zh">前扰流板</span></h3>

        <div className="bilingual">
          <p lang="en">
            These components are designed to control airflow beneath the car and reduce lift. However, if poorly designed or improperly installed, they can disrupt airflow and increase pressure under the body, reducing stability. In extreme cases, this can lead to a significant loss of control.
          </p>
          <p lang="zh">
            目的是抑制气流进入车身下面、降低升力。不过虽属极少见情形：装上整形不足的零件，又降低最低离地间隙以求低重心时，加压气流会接连涌入被收窄的车底，与本来目的相反在前部产生升力，最坏会失控。要化解并利用行驶风。
          </p>
        </div>

        <p className="image">
          <img alt="" src={i16xDdiIScrECTH} />
        </p>

        <h3 className="bilingual-title"><span lang="en">Rear Bumper Spoiler</span><span className="bilingual-sep"> / </span><span lang="zh">后保险杠扰流</span></h3>

        <div className="bilingual">
          <p lang="en">
            These components are designed to shape airflow around the rear bumper, helping to reduce turbulence and improve overall aerodynamic efficiency. They can be integrated into the bumper as a single unit or added as a separate attachment beneath it. The integrated type is often referred to as a rear bumper spoiler, while the add-on type is commonly called a rear under spoiler or rear skirt.
          </p>
          <p lang="zh">
            优化后保险杠形状、抑制后方涡流产生，使气流顺畅导向后方的空力件。有与后杠一体式，以及装在后杠下部两类；一般前者称「后保险杠扰流」，后者称「后下扰流」或「后裙」等。
          </p>
        </div>

        <p className="image">
          <img alt="" src={i1PE93sKsGeGNb} />
        </p>

        <h3 className="bilingual-title"><span lang="en">Side Spoiler</span><span className="bilingual-sep"> / </span><span lang="zh">侧裙</span></h3>

        <div className="bilingual">
          <p lang="en">
            Also known as side skirts or side steps, these are mounted along the side sills of the body. They help manage airflow along the sides of the car and can reduce turbulence.
          </p>
          <p lang="zh">
            亦称侧裙、侧踏板等，装于车身两侧下部（侧梁附近），有降低车身侧面空气阻力的效果。
          </p>
        </div>

        <p className="image">
          <img alt="" src={i1UoGnYMFM90Sz} />
        </p>

        <h3 className="bilingual-title"><span lang="en">Rear Wing</span><span className="bilingual-sep"> / </span><span lang="zh">尾翼</span></h3>

        <div className="bilingual">
          <p lang="en">
            Mounted on the upper rear of the body, rear wings help manage airflow and generate downforce. Their shape is designed to reduce lift and improve high-speed stability. Larger wings can produce greater downforce, increasing load on the rear tires and improving grip, although this is often accompanied by increased drag.
          </p>
          <p lang="zh">
            装于车身后部上方，带来使气流顺畅导向后方的整流效果，并抑制后方涡流。把产生升力的飞机机翼反过来的扰流形状，尺寸一大可产生强下压力，可期待提高后轮抓地力。
          </p>
        </div>

        <p className="image">
          <img alt="" src={i1Cf1luD0oa5scc} />
        </p>

        <h3 className="bilingual-title"><span lang="en">Rear Diffuser</span><span className="bilingual-sep"> / </span><span lang="zh">尾部扩散器</span></h3>

        <div className="bilingual">
          <p lang="en">
            Rear diffusers are fitted beneath the rear of the car and work by accelerating airflow from the underbody, helping to lower pressure and generate downforce. They are widely used in racing applications, and their effectiveness depends on factors such as ride height and overall underbody airflow.
          </p>
          <p lang="zh">
            把流经车身下部（底板）的风从后保险杠下方高效导出以产生负压、获得下压力的整流板。赛车普遍使用；底板与路面间隙越窄效果越大。
          </p>
        </div>

        <p className="image">
          <img alt="" src={i1W6VS3qRqQcxuB} />
        </p>
      </div>
    </div>
  </>
);

export default AerodynamicTuning;
