import i1sXpmIVjN3UpW from "../../assets/images/i1sXpmIVjN3UpW.webp";
import i1KwIRbUuewX4z from "../../assets/images/i1KwIRbUuewX4z.webp";
import i1PgxQYcZA0L2cc from "../../assets/images/i1PgxQYcZA0L2cc.webp";
import i1GsXxew1QPblb from "../../assets/images/i1GsXxew1QPblb.webp";
import i1LAkv2jDxtCH from "../../assets/images/i1LAkv2jDxtCH.webp";
import i15NS2WmoSAxUuH from "../../assets/images/i15NS2WmoSAxUuH.webp";
import i1Cjg1O9tpbYj from "../../assets/images/i1Cjg1O9tpbYj.webp";

const BodyRollAndVehicleMotion = () => (
  <>
    <div className="manual_detail">
      <div className="content_header">
        <h1>2-5 : Body Roll and Vehicle Motion / 车身侧倾与车辆运动</h1>
        <h2>
          Utilizing body roll to adjust steering characteristic /
          利用侧倾运动调整转向特性
        </h2>
      </div>
      <div className="body">
        <div className="bilingual">
          <p lang="en">
            The body of the car rolls outward during cornering. Up to this point, we have intentionally omitted the effects of body roll to simplify our discussions. However, vehicle motion is greatly influenced by body roll. Let us explore the effects of body roll in relation to overall vehicle performance.
          </p>
          <p lang="zh">
            转弯时车身会向外侧侧倾。此前为简化讨论，我们有意忽略了侧倾的影响；但车辆运动实际上受侧倾影响很大。下面考察侧倾对整体车辆性能的作用。
          </p>
        </div>

        <p className="image">
          <img alt="" src={i1sXpmIVjN3UpW} />
        </p>
        <div className="bilingual">
          <p className="caption" lang="en">
            Fig. 2-5-1.
          </p>
          <p className="caption" lang="zh">
            图2-5-1。
          </p>
        </div>

        <h3 className="section-header">
          ● Effects of body roll on steering characteristic /
          侧倾对转向特性的影响
        </h3>

        <div className="bilingual">
          <p lang="en">
            From Fig. 2-5-2, we can observe that even if the load is doubled, the cornering force does not increase by the same amount. This is due to diminishing returns in cornering force as load increases, producing a saturation curve. During cornering, load transfers from the inner wheel to the outer wheel. As a result, the combined cornering force of the inner and outer wheels is lower than it would be without load transfer. In other words, the greater the load transfer, the smaller the total cornering force.
          </p>
          <p lang="zh">
            由图 2-5-2 可见，即使载荷加倍，侧偏力也不会按同样比例增加——载荷升高时侧偏力增幅逐渐变缓，呈饱和曲线。转弯时载荷由内轮向外轮转移，因此内外轮侧偏力之和会低于无载荷转移时；换言之，载荷转移越大，总侧偏力越小。
          </p>
        </div>

        <p className="image">
          <img alt="" src={i1KwIRbUuewX4z} />
        </p>
        <div className="bilingual">
          <p className="caption" lang="en">
            Fig. 2-5-2: Relationship between tire load and cornering power. Load and cornering power are not proportional; therefore, even if the load doubles, the cornering power does not double.
          </p>
          <p className="caption" lang="zh">
            图2-5-2：轮胎载荷与侧偏刚度的关系。二者不成正比，故载荷加倍时侧偏刚度也不会加倍。
          </p>
        </div>

        <p className="image">
          <img alt="" src={i1PgxQYcZA0L2cc} />
        </p>
        <div className="bilingual">
          <p className="caption" lang="en">
            Fig. 2-5-3: Comparison between a car with a large amount of weight transfer and one with a smaller amount. For a car with less weight transfer, the cornering force (F1) is equal to one-half of the sum of the inner wheel (A) and outer wheel (B). For a car with greater weight transfer, the cornering force (F2) is also one-half of the sum of A&apos; and B&apos;, but the total is reduced due to load sensitivity. A car with less weight transfer therefore produces a larger total cornering force.
          </p>
          <p className="caption" lang="zh">
            图2-5-3：载荷转移大与小的对比。转移较小时，侧偏力 F1 为内轮 A 与外轮 B 之和的一半；转移较大时，F2 为 A′ 与 B′ 之和的一半，但因载荷敏感性总和更小。因此载荷转移较小的车辆总侧偏力更大。
          </p>
        </div>

        <h3 className="section-header">
          ● Steering characteristics when the load transfer differs between front
          and rear / 前后载荷转移不同时的转向特性
        </h3>

        <div className="bilingual">
          <p lang="en">
            Because the generation of cornering force varies with vertical load in a nonlinear, saturating manner, differences in load transfer between the front and rear tires will affect the steering characteristics. If the load transfer at the front wheels is greater than at the rear wheels, the vehicle will tend to understeer. If the load transfer at the front wheels is less than at the rear wheels, the vehicle will tend to oversteer.
            <br />
            <br />
            The amount of lateral load transfer between the left and right sides is determined by the balance between the external moment generated by lateral forces and the resisting moment provided by the vehicle’s roll stiffness. This relationship is influenced primarily by front and rear roll center heights, roll stiffness distribution, and track width. In simplified terms, roll center height affects the moment generated by lateral tire forces, roll stiffness distribution governs how that moment is shared between the front and rear, and track width influences how load transfer is distributed across the tires. These relationships determine the magnitude and distribution of load transfer, helping to explain the effects of body roll on steering characteristics, as summarized in Chart 2-5-1.
          </p>
          <p lang="zh">
            侧偏力随垂直载荷呈非线性饱和变化，因此前后载荷转移不同会改变转向特性：前轮载荷转移大于后轮时倾向不足转向；前轮小于后轮时倾向过度转向。
            <br />
            <br />
            左右横向载荷转移量，由侧向力产生的外部力矩与车辆侧倾刚度产生的抵抗力矩之间的平衡决定。这一关系主要受前后侧倾中心高度、侧倾刚度分配与轮距影响。简言之：侧倾中心高度影响轮胎侧向力产生的力矩；侧倾刚度分配决定该力矩如何在前后分担；轮距影响载荷转移在轮胎上的分配。这些关系决定载荷转移的大小与分配，从而解释侧倾对转向特性的影响，归纳见表 2-5-1。
          </p>
        </div>

        <p className="image">
          <img alt="" src={i1GsXxew1QPblb} />
        </p>
        <div className="bilingual">
          <p className="caption" lang="en">
            Chart 2-5-1: Change in steer characteristics and suspension tuning.
          </p>
          <p className="caption" lang="zh">
            表2-5-1：悬架调校与转向特性的变化。
          </p>
        </div>

        <div className="images">
          <dl className="image_list">
            <dd>
              <img alt="" src={i1LAkv2jDxtCH} />
            </dd>
            <dd className="caption">
              <div className="bilingual">
                <p lang="en">
                  Understeer increases by raising the front roll center height
                  or by lowering the rear roll center height.
                </p>
                <p lang="zh">
                  提高前轮侧倾中心，或降低后轮侧倾中心，会使不足转向增强。
                </p>
              </div>
            </dd>
          </dl>

          <dl className="image_list">
            <dd>
              <img alt="" src={i15NS2WmoSAxUuH} />
            </dd>
            <dd className="caption">
              <div className="bilingual">
                <p lang="en">
                  Understeer increases by raising the front roll stiffness
                  relative to the rear.
                </p>
                <p lang="zh">
                  提高前轴相对后轴的侧倾刚度分配，会使不足转向增强。
                </p>
              </div>
            </dd>
          </dl>

          <dl className="image_list">
            <dd>
              <img alt="" src={i1Cjg1O9tpbYj} />
            </dd>
            <dd className="caption">
              <div className="bilingual">
                <p lang="en">
                  Understeer increases by reducing the front track width or
                  increasing the rear track width.
                </p>
                <p lang="zh">
                  减小前轮轮距，或增大后轮轮距，会使不足转向增强。
                </p>
              </div>
            </dd>
          </dl>
        </div>
      </div>
    </div>
  </>
);

export default BodyRollAndVehicleMotion;
