import i1GZ2tQPAZkgN from "../../assets/images/i1GZ2tQPAZkgN.webp";
import i1UoFMeHLrYkKEc from "../../assets/images/i1UoFMeHLrYkKEc.webp";
import i1bpN9qvxg31rb from "../../assets/images/i1bpN9qvxg31rb.webp";
import i1jbETgqfSdN9SH from "../../assets/images/i1jbETgqfSdN9SH.webp";

const SuspensionsConstructionAndPrinciples = () => (
  <>
    <div className="manual_detail">
      <div className="content_header">
        <h1>Construction and Principles / 结构与原理</h1>
      </div>
      <div className="body">
        <div className="bilingual">
          <p lang="en">
            The suspension is the system between the body and the wheels that absorbs shocks from the road while supporting the vehicle. It also plays a key role in handling, making it a critical part of a car’s design.
          </p>
          <p lang="zh">
            悬架是支承车身、吸收轮胎所受冲击的机构，对操控稳定性也有重大影响，是关键的行驶机构。
          </p>
        </div>

        <div className="bilingual">
          <p lang="en">
            Suspension systems are broadly classified as dependent or independent. In a dependent system, movement of one wheel affects the other on the same axle. In an independent system, the left and right wheels move separately. Dependent layouts include beam or live axles, while independent designs include strut-type and double wishbone suspension.
          </p>
          <p lang="zh">
            悬架大致分为固定式（一侧车轮运动会影响另一侧）与独立式（左右车轮独立运动）。固定式代表有车轴式、连杆式、扭力梁式等；独立式有麦弗逊支柱式、双叉臂式等。
          </p>
        </div>

        <div className="bilingual">
          <p lang="en">
            The suspension is made up of springs, dampers and linkages. The springs absorb impacts from the road, while the dampers control spring motion to maintain ride comfort and stability. The linkages guide wheel movement, helping the tires maintain consistent contact with the road. Together, the system supports the vehicle and manages how forces are transmitted through the tires.
          </p>
          <p lang="zh">
            悬架由弹簧、减振器与连杆（臂）组成。弹簧缓和路面冲击，减振器抑制弹簧振动以改善舒适与稳定，连杆约束车轮运动使轮胎最佳接地。悬架还以弹簧反力将轮胎压向路面并决定其位置，作用重大。
          </p>
        </div>

        <div className="bilingual">
          <p lang="en">
            The illustration shows a strut-type suspension. First developed by Earle S. MacPherson, it has become one of the most widely used suspension layouts in production cars. In this design, the strut assembly serves a structural role, effectively replacing the upper control arm found in a double wishbone setup. This reduces component count and helps free up space in the engine bay.
          </p>
          <p lang="zh">
            图示为麦弗逊支柱式悬架，是大量车型采用的典型形式。支柱壳体兼作双叉臂的上控制臂，零件少，发动机舱空间更大。
          </p>
        </div>

        <p className="image">
          <img alt="" src={i1bpN9qvxg31rb} />
        </p>

        <div className="bilingual">
          <p className="caption" lang="en">
            Example of strut-type suspension
          </p>
          <p className="caption" lang="zh">
            【麦弗逊支柱式悬架示例】
          </p>
        </div>

        <h3>
          Springs / 弹簧
        </h3>

        <div className="bilingual">
          <p lang="en">
            Springs absorb impacts from the road and help maintain a consistent ride height. They play a key role in controllability, and have a major influence on handling and stability. Spring tuning alone can significantly affect a car’s performance. Most vehicles use steel coil springs, although some are equipped with air suspension systems.
          </p>
          <p lang="zh">
            弹簧首先承受行驶冲击并缓和震动，同时维持一定车高。对操控性、弯道性能与稳定性影响极大，仅弹簧设定就能显著改变车辆性格。金属螺旋弹簧最常见，亦有利用气压的空气悬架。
          </p>
        </div>

        <p className="image">
          <img alt="" src={i1jbETgqfSdN9SH} />
        </p>

        <h3>
          Shock Absorbers / 减振器
        </h3>

        <div className="bilingual">
          <p lang="en">
            A coil spring can absorb an impact under load, but once compressed, it will continue to oscillate. Dampers control this motion. The most common type uses resistance generated by a piston moving through oil, often with gas pressure to improve performance. By slowing the spring’s movement, the damper reduces unwanted vertical motion. Like springs, dampers play a key role in control and stability.
          </p>
          <p lang="zh">
            螺旋弹簧受压伸缩缓冲，但会持续振荡；减振器（减震器）抑制这一运动。常见为活塞在油液或油气中运动产生阻力，“慢缩慢回”以衰减弹簧剧烈跳动，同样左右操控与稳定。
          </p>
        </div>

        <p className="image">
          <img alt="" src={i1GZ2tQPAZkgN} />
        </p>

        <h3>
          Suspension Arms / 悬架臂
        </h3>

        <div className="bilingual">
          <p lang="en">
            Suspension arms control wheel movement. They connect the wheel assembly to the body or subframe through bushings. Common types include A-arms, or wishbones. They are typically made from steel, although aluminum is often used in performance applications to reduce weight. In layouts with two arms per wheel, such as double wishbone suspension, they are referred to as upper and lower control arms.
          </p>
          <p lang="zh">
            控制车轮运动的部件，亦称控制臂，经衬套连车身或副车架。有A臂、I臂等形状，多为钢板冲压，性能车常用锻造铝减重。双叉臂上下成对时，上为 upper arm、下为 lower arm。
          </p>
        </div>

        <h3>
          Suspension Bushings / 悬架衬套
        </h3>

        <div className="bilingual">
          <p lang="en">
            Suspension bushings are compliant components fitted at the joints of suspension links and arms, as well as other mounting points on the body. If they are too soft, they can deform under load during cornering, introducing unwanted movement and reducing control and stability. For this reason, bushings are typically made from rubber compounds that balance compliance and durability. In competition cars, rigid spherical joints, often called pillow-ball joints, are used instead to maximize precision. Bushings play an important role in allowing the springs and dampers to function as intended.
          </p>
          <p lang="zh">
            连杆、臂结合部及车身安装处的缓冲件。过软会在弯道大载荷下变形，产生多余运动、损害操控稳定。多用橡胶平衡柔顺与耐久；赛车常用金属球窝接头（pillow ball）以精确传递。对发挥弹簧与减振器性能也很重要。
          </p>
        </div>

        <h3>
          Sway Bars/Stabilizers / 防倾杆
        </h3>

        <div className="bilingual">
          <p lang="en">
            A sway bar, or stabilizer, is a device that reduces body roll by using the torsional resistance of a bar connecting the left and right suspension. It is also known as an anti-roll bar. The bar links both sides of the suspension and primarily reacts to differences in movement between them. When cornering, the outside suspension compresses while the inside extends. The sway bar resists this difference, helping to limit roll and stabilize the vehicle. By adjusting its stiffness, it can also be used to influence understeer and oversteer balance.
          </p>
          <p lang="zh">
            利用连接左右悬架的扭杆刚度抑制侧倾的稳定装置，亦称防倾杆。两端接在下控制臂，仅在左右车轮运动不一致时起作用：过弯外侧压缩、内侧伸展时，限制差异以稳定姿态；调整刚度亦可调校不足/过度转向平衡。
          </p>
        </div>

        <p className="image">
          <img alt="" src={i1UoFMeHLrYkKEc} />
        </p>
      </div>
    </div>
  </>
);

export default SuspensionsConstructionAndPrinciples;
