import i1DKbX1sVlR9rz from "../../assets/images/i1DKbX1sVlR9rz.webp";
import i1Y1WKUT6Forrcc from "../../assets/images/i1Y1WKUT6Forrcc.webp";
import i1J3hvb0uPjDO from "../../assets/images/i1J3hvb0uPjDO.webp";
import i1EICYkzzRzRKSH from "../../assets/images/i1EICYkzzRzRKSH.webp";

const TireDynamics = () => (
  <>
    <div className="manual_detail">
      <div className="content_header">
        <h1>2-1 : Tire Dynamics / 轮胎的力学</h1>
        <h2>
          Understanding the forces created by the tire /
          首先理解轮胎所产生的力
        </h2>
      </div>
      <div className="body">
        <h3 className="section-header">● Cornering force / 侧偏力</h3>

        <div className="bilingual">
          <p lang="en">
            The type of force that deforms an object in a shearing manner is called shear force, and the material property that resists this deformation is called the shear modulus. When a tire is subjected to lateral forces, it deforms in shear as shown in Fig. 2-1-1. At the same time, the shear stiffness of the tire resists this deformation. This resisting behavior of the tire generates the forces required for the car to accelerate, decelerate and turn.
          </p>
          <p lang="zh">
            使物体发生剪切变形的力称为剪切力，而材料抵抗这种变形的性质称为剪切模量。当轮胎受到横向力时，会如图 2-1-1 所示发生剪切变形；与此同时，轮胎的剪切刚度会抵抗这一变形。正是轮胎对自身变形的这种反抗，产生了汽车加速、减速与转向所需的力。
          </p>
        </div>

        <p className="image">
          <img alt="" src={i1DKbX1sVlR9rz} />
        </p>
        <div className="bilingual">
          <p className="caption" lang="en">
            Fig. 2-1-1: Cross-section diagram illustrating tire deformation and force. In general, greater lateral stiffness results in a larger cornering force.
          </p>
          <p className="caption" lang="zh">
            图2-1-1：横截面示意轮胎变形与力的关系。一般而言，横向刚度越大，产生的侧偏力也越大。
          </p>
        </div>

        <div className="bilingual">
          <p lang="en">
            Fig. 2-1-2 is a sectional illustration of a tire during cornering. As shown, there is a difference between the orientation of the tire and the direction of travel of the vehicle. In other words, force is generated through the interaction between the tire and the road surface as the tire both rotates and deforms laterally. The angle between the tire’s orientation and the direction of travel is called the slip angle. The force acting perpendicular to the direction of travel is called cornering force. A vehicle is able to turn because of the cornering force generated by the tire.
            <br />
            <br />
            In general, if the tire’s lateral stiffness is higher, a greater cornering force can be produced for the same slip angle. However, if the stiffness is too high, the tire can reach its grip limit at a small slip angle, which may result in less progressive feedback to the driver. If the stiffness is too low, the tire will deform excessively, which can make the vehicle feel unstable and reduce driver confidence.
          </p>
          <p lang="zh">
            图 2-1-2 是转弯中轮胎的示意截面。可以看到，轮胎朝向与车辆行驶方向并不一致：轮胎在旋转的同时发生横向变形，通过与路面的相互作用产生力。轮胎朝向与行驶方向之间的夹角称为侧偏角；垂直于行驶方向的力称为侧偏力。车辆之所以能够转向，正是因为轮胎产生了侧偏力。
            <br />
            <br />
            一般而言，轮胎横向刚度越高，在相同侧偏角下能产生的侧偏力越大。但刚度过高时，轮胎会在很小的侧偏角就达到抓地极限，驾驶员得到的渐进反馈可能变少；刚度过低时，轮胎变形过大，又会让车辆感觉不稳，削弱驾驶信心。
          </p>
        </div>

        <p className="image">
          <img alt="" src={i1Y1WKUT6Forrcc} />
        </p>
        <div className="bilingual">
          <p className="caption" lang="en">
            Fig. 2-1-2: Top view of a tire illustrating the relationship between deformation and force. Lateral force acts perpendicular to the direction of travel. Cornering force refers to the lateral force generated by the tire due to slip angle.
          </p>
          <p className="caption" lang="zh">
            图2-1-2：俯视示意轮胎变形与力的关系。横向力垂直于行驶方向；侧偏力是因侧偏角而由轮胎产生的横向力。
          </p>
        </div>

        <h3 className="section-header">
          ● Relation between cornering force and slip angle /
          侧偏力与侧偏角的关系
        </h3>

        <div className="bilingual">
          <p lang="en">
            Fig. 2-1-3 shows the relationship between slip angle and cornering force. When the slip angle is small, the cornering force increases approximately linearly. However, as the slip angle becomes larger, the cornering force begins to saturate. The rate of change of cornering force with respect to slip angle is called cornering power. A tire that generates a large cornering force at a small slip angle can be said to have high cornering power.
          </p>
          <p lang="zh">
            图 2-1-3 给出了侧偏角与侧偏力的关系。侧偏角较小时，侧偏力近似线性上升；侧偏角继续增大后，侧偏力开始饱和。侧偏力相对侧偏角的变化率称为侧偏刚度（cornering power）。在较小侧偏角下就能产生较大侧偏力的轮胎，可以说侧偏刚度较高。
          </p>
        </div>

        <p className="image">
          <img alt="" src={i1J3hvb0uPjDO} />
        </p>
        <div className="bilingual">
          <p className="caption" lang="en">
            Fig. 2-1-3: Correlation between slip angle and cornering force. Cornering power is high in the range where the slip angle is relatively small. As the slip angle increases, the cornering force begins to saturate and the rate of increase diminishes.
          </p>
          <p className="caption" lang="zh">
            图2-1-3：侧偏角与侧偏力的关系。侧偏角较小时侧偏刚度较高；侧偏角增大后侧偏力趋于饱和，增长率下降。
          </p>
        </div>

        <h3 className="section-header">
          ● Air pressure and cornering power / 气压与侧偏刚度
        </h3>

        <div className="bilingual">
          <p lang="en">
            In general, when tire pressure is relatively low, increasing the pressure raises the tire’s lateral stiffness, which can increase cornering power. However, increasing pressure also reduces the contact area of the tire. As pressure rises, these two effects oppose each other. At low vertical loads, the reduction in contact area due to higher pressure is more significant than the increase in stiffness, resulting in a decrease in cornering power. On the other hand, at higher vertical loads, the increase in stiffness becomes dominant, leading to an increase in cornering power. To maximize cornering power, the characteristics of the tire and the applied load must be carefully considered and balanced.
          </p>
          <p lang="zh">
            一般而言，在气压偏低的范围内提高气压，会提高轮胎的横向刚度，从而可能增大侧偏刚度。但升压也会减小接地面积。随着气压上升，这两种效应相互对抗：垂直载荷较小时，接地面积减小的影响往往大于刚度增加，侧偏刚度反而下降；垂直载荷较大时，刚度增加占主导，侧偏刚度随之上升。要最大限度获得侧偏刚度，必须结合轮胎特性与载荷仔细权衡。
          </p>
        </div>

        <h3 className="section-header">
          ● Lateral force of the tire associated with driving and braking /
          伴随驱动与制动的轮胎横向力
        </h3>

        <div className="bilingual">
          <p lang="en">
            Viewed from above, the force generated perpendicular to the tire’s direction of travel is called lateral force. It is important to understand how this lateral force is related to the driving and braking of the vehicle. When the accelerator or brake is applied, the tire’s available grip is shared between longitudinal force (driving or braking) and lateral force. As a result, the amount of lateral force that can be generated at a given slip angle is reduced. This relationship is illustrated in Fig. 2-1-4. Although it is often referred to as a friction circle, the diagram is typically oval in shape rather than perfectly circular, since longitudinal and lateral forces influence the tire differently. Because acceleration and braking are continuously combined in racing conditions, the tire’s ability to generate force in combined directions has a significant effect on lap times.
          </p>
          <p lang="zh">
            从上方看，垂直于轮胎行驶方向产生的力称为横向力。理解横向力与车辆驱动、制动的关系很重要：踩下油门或刹车时，轮胎可用的抓地力会在纵向力（驱动或制动）与横向力之间分配，因此在同一侧偏角下可产生的横向力会减小。这一关系如图 2-1-4 所示。尽管常被称为摩擦圆，图中边界通常呈椭圆而非正圆——因为纵向与横向对轮胎的影响并不相同。赛车中加速与制动常与转向叠加，轮胎在复合方向上产生力的能力会显著影响圈速。
          </p>
        </div>

        <p className="image">
          <img alt="" src={i1EICYkzzRzRKSH} />
        </p>
        <div className="bilingual">
          <p className="caption" lang="en">
            Fig. 2-1-4: Friction circle. The cornering force of the tire is influenced by slip angle. The oval perimeter represents the limit of combined tire force, including both lateral and longitudinal components.
          </p>
          <p className="caption" lang="zh">
            图2-1-4：摩擦圆。轮胎侧偏力受侧偏角影响；椭圆边界表示含横向与纵向分量的轮胎合力极限。
          </p>
        </div>
      </div>
    </div>
  </>
);

export default TireDynamics;
