import i1Kx0PqNJkrLQSB from "../../assets/images/i1Kx0PqNJkrLQSB.webp";
import i1QTArcWtOMm4 from "../../assets/images/i1QTArcWtOMm4.webp";
import i1dvybpzM9rPAuH from "../../assets/images/i1dvybpzM9rPAuH.webp";
import i1nWmE2CM0SJRb from "../../assets/images/i1nWmE2CM0SJRb.webp";
import i1zhvFQ1Noh8AEE from "../../assets/images/i1zhvFQ1Noh8AEE.webp";

const UnsprungWeight = () => (
  <>
    <div className="manual_detail">
      <div className="content_header">
        <h1>Unsprung Weight / 非簧载质量</h1>
      </div>
      <div className="body">
        <div className="bilingual">
          <p lang="en">
            Although often seen as a styling feature, aluminum wheels have a significant effect on driving performance.
            <br />
            <br />
            A car requires the most torque when accelerating from a standstill. Rotating the wheels from rest takes energy, and heavier wheels require more of it. Lighter wheels reduce rotational inertia, making acceleration easier and reducing the load on the engine.
            <br />
            <br />
            Weight not supported by the suspension is known as unsprung mass and has a major influence on vehicle behavior. Lighter wheels and tires improve acceleration, braking and ride quality, as the suspension can respond more effectively to the road surface. Reduced weight can also contribute to improved fuel efficiency.
            <br />
            <br />
            The popularity of aluminum wheels in sports cars reflects the performance benefits they offer. In motorsport, unsprung mass is often reduced further with magnesium alloy wheels, which are even lighter than aluminum.
            <br />
            <br />
            Aluminum wheels also conduct heat efficiently, helping dissipate heat generated by the brakes, and they are generally more resistant to corrosion than steel wheels.
            <br />
            <br />
            Care must be taken when changing wheel size, as increasing diameter can offset the weight advantage of lighter materials. Larger wheels tend to increase unsprung mass, so the benefits of lower-profile tires must be balanced against the drawbacks of added weight.
          </p>
          <p lang="zh">
            铝轮毂不仅是造型件，对性能影响显著：减轻非簧载质量可改善悬架贴地与响应，是运动化改装的常见手段。
          </p>
        </div>

        <p className="image">
          <img alt="" src={i1zhvFQ1Noh8AEE} />
        </p>

        <div className="bilingual">
          <p lang="en">
            The lighter the wheel, the better the tire can follow the road surface, improving ride quality and stability.
          </p>
          <p lang="zh">
            轮越轻，轮胎越能跟随路面，改善抓地与舒适。
          </p>
        </div>

        <p className="image">
          <img alt="" src={i1nWmE2CM0SJRb} />
        </p>

        <div className="bilingual">
          <p lang="en">
            Lower wheel weight reduces the energy required to set the car in motion.
          </p>
          <p lang="zh">
            更轻的轮毂可降低使车辆运动所需的能量。
          </p>
        </div>

        <h3 className="section-header">
          ● Types of Lightweight Wheels / ● 轻量化轮毂种类
        </h3>

        <h3>
          One-Piece / 单片式
        </h3>

        <div className="bilingual">
          <p lang="en">
            A one-piece wheel is made with the rim and disc formed as a single unit. After casting or forging, it is machined to achieve a high level of precision. Design flexibility is more limited, but the one-piece construction allows for lower weight and good balance compared with multi-piece wheels.
          </p>
          <p lang="zh">
            轮辋与轮盘一体成型，成本低，量产最常见。
          </p>
        </div>

        <p className="image">
          <img alt="" src={i1Kx0PqNJkrLQSB} />
        </p>

        <h3>
          Two-Piece / 两片式
        </h3>

        <div className="bilingual">
          <p lang="en">
            A two-piece wheel has the disc and rim manufactured separately and then joined, typically with bolts or by welding. Different materials and production methods can be used for each section, including aluminum, magnesium or titanium, and either casting or forging. This construction allows greater flexibility in design, particularly in disc styling and offset.
          </p>
          <p lang="zh">
            轮盘与轮辋分别制造再结合，可换规格，改装与赛车常见。
          </p>
        </div>

        <p className="image">
          <img alt="" src={i1QTArcWtOMm4} />
        </p>

        <h3>
          Three-Piece / 三片式
        </h3>

        <div className="bilingual">
          <p lang="en">
            A three-piece wheel is made from separate inner and outer rim sections, with the center disc attached using perimeter bolts. Like two-piece designs, it offers flexibility in materials and construction, along with a wide range of styling and offset options. The additional hardware can add weight, but it allows even greater design freedom, making this type popular for custom and high-end applications.
          </p>
          <p lang="zh">
            内、外轮辋与轮盘三件组合，尺寸与宽度组合自由，高端改装与赛车用。
          </p>
        </div>

        <p className="image">
          <img alt="" src={i1dvybpzM9rPAuH} />
        </p>

        <h3 className="section-header">
          ● Manufacturing Methods / ● 制造方法
        </h3>

        <h3>
          Casting / 铸造
        </h3>

        <div className="bilingual">
          <p lang="en">
            Casting is a manufacturing method in which molten aluminum is poured into a mold. It allows a high degree of design flexibility, particularly for the wheel center. However, to achieve sufficient strength, the material often needs to be thicker, which can limit weight savings compared with steel wheels. Even so, its low cost makes casting the most common method for producing aluminum wheels.
          </p>
          <p lang="zh">
            熔融铝浇入模具成型，成本低产量大，强度与重量居中。
          </p>
        </div>

        <h3>
          Forging / 锻造
        </h3>

        <div className="bilingual">
          <p lang="en">
            In forging, a block of metal is compressed under extremely high pressure, aligning its internal grain structure and producing a dense, strong material. Compared with casting, the material is stronger, allowing for thinner sections and reduced weight. The result is high strength and rigidity, along with improved resistance to fatigue. Forging is more expensive and offers less design flexibility than casting. While aluminum is most common, magnesium is also used in some racing and high-performance applications for further weight reduction.
          </p>
          <p lang="zh">
            铝坯高压锻打，晶粒流向优化，同强度更轻、更刚，高性能与赛车首选，成本较高。
          </p>
        </div>
      </div>
    </div>
  </>
);

export default UnsprungWeight;
