import i1Kx0PqNJkrLQSB from "../../assets/images/i1Kx0PqNJkrLQSB.webp";
import i1QTArcWtOMm4 from "../../assets/images/i1QTArcWtOMm4.webp";
import i1dvybpzM9rPAuH from "../../assets/images/i1dvybpzM9rPAuH.webp";
import i1nWmE2CM0SJRb from "../../assets/images/i1nWmE2CM0SJRb.webp";
import i1zhvFQ1Noh8AEE from "../../assets/images/i1zhvFQ1Noh8AEE.webp";

const UnsprungWeight = () => (
  <>
    <div className="manual_detail">
      <div className="content_header">
        <h1>Unsprung Weight / 簧下质量</h1>
      </div>
      <div className="body">
        <div className="bilingual">
          <p lang="en">
            Although often seen as a styling feature, aluminum wheels have a significant effect on driving performance.
          </p>
          <p lang="zh">
            铝制轮毂虽多被当作装饰件，对行驶性能的影响却不小。
          </p>
        </div>

        <div className="bilingual">
          <p lang="en">
            A car requires the most torque when accelerating from a standstill. Rotating the wheels from rest takes energy, and heavier wheels require more of it. Lighter wheels reduce rotational inertia, making acceleration easier and reducing the load on the engine.
          </p>
          <p lang="zh">
            汽车最需要动力的是起步：使静止车轮转出第一圈需要很大能量。轮毂越重越难转动，越轻则越能以较少能量（发动机功率）轻松转动。
          </p>
        </div>

        <div className="bilingual">
          <p lang="en">
            Weight not supported by the suspension is known as unsprung mass and has a major influence on vehicle behavior. Lighter wheels and tires improve acceleration, braking and ride quality, as the suspension can respond more effectively to the road surface. Reduced weight can also contribute to improved fuel efficiency.
          </p>
          <p lang="zh">
            这就是所谓「簧下质量」，对车辆运动性影响很大。轮毂与轮胎变轻，起步·加速更好，制动时也更容易停住车轮（刹车更有效）；悬架动作更顺畅，路面跟随与乘坐改善，油耗也有利。
          </p>
        </div>

        <div className="bilingual">
          <p lang="en">
            The popularity of aluminum wheels in sports cars reflects the performance benefits they offer. In motorsport, unsprung mass is often reduced further with magnesium alloy wheels, which are even lighter than aluminum.
          </p>
          <p lang="zh">
            多数跑车原厂采用比重低于钢铁的铝轮毂，便是最好的证明；其效果甚至有「簧下减重 1 kg 约等于簧上减重 15 kg」之说。赛车世界还会用比铝更轻的镁合金或碳纤维轮毂。
          </p>
        </div>

        <div className="bilingual">
          <p lang="en">
            Aluminum wheels also conduct heat efficiently, helping dissipate heat generated by the brakes, and they are generally more resistant to corrosion than steel wheels.
          </p>
          <p lang="zh">
            主流铝轮毂导热与热容量也好，能高效排出制动热，耐腐蚀性也优于铸铁制轮毂。
          </p>
        </div>

        <div className="bilingual">
          <p lang="en">
            Care must be taken when changing wheel size, as increasing diameter can offset the weight advantage of lighter materials. Larger wheels tend to increase unsprung mass, so the benefits of lower-profile tires must be balanced against the drawbacks of added weight.
          </p>
          <p lang="zh">
            更换轮毂时须注意：放大尺寸可能反而增重。尤其大幅加大时，多数会增加簧下质量，须权衡低扁平比轮胎的好处与重量增加的坏处。
          </p>
        </div>

        <p className="image">
          <img alt="" src={i1zhvFQ1Noh8AEE} />
        </p>

        <div className="bilingual">
          <p className="caption" lang="en">
            The lighter the wheel, the better the tire can follow the road surface, improving ride quality and stability.
          </p>
          <p className="caption" lang="zh">
            轮毂变轻后，轮胎对路面的跟随性提高，乘坐也更趋于平顺。
          </p>
        </div>

        <p className="image">
          <img alt="" src={i1nWmE2CM0SJRb} />
        </p>

        <div className="bilingual">
          <p className="caption" lang="en">
            Lower wheel weight reduces the energy required to set the car in motion.
          </p>
          <p className="caption" lang="zh">
            轮毂变轻，也能减轻车辆起步时对发动机功率的需求。
          </p>
        </div>

        <h3 className="section-header">
          ● Types of Lightweight Wheels / ● 结构
        </h3>

        <h3>
          One-Piece / 单片式
        </h3>

        <div className="bilingual">
          <p lang="en">
            A one-piece wheel is made with the rim and disc formed as a single unit. After casting or forging, it is machined to achieve a high level of precision. Design flexibility is more limited, but the one-piece construction allows for lower weight and good balance compared with multi-piece wheels.
          </p>
          <p lang="zh">
            轮辋与轮盘一体成型的最基本结构。铸造（或锻造）后再切削精加工，尺寸精度高。设计自由度相对较小，但零件少，比两片式、三片式更轻，重量平衡也更好。
          </p>
        </div>

        <p className="image">
          <img alt="" src={i1Kx0PqNJkrLQSB} />
        </p>

        <h3>
          Two-Piece / 两片式
        </h3>

        <div className="bilingual">
          <p lang="en">
            A two-piece wheel has the disc and rim manufactured separately and then joined, typically with bolts or by welding. Different materials and production methods can be used for each section, including aluminum, magnesium or titanium, and either casting or forging. This construction allows greater flexibility in design, particularly in disc styling and offset.
          </p>
          <p lang="zh">
            轮盘与轮辋分别制造，再用螺栓螺母或焊接结合。两部可用不同材料（铝、镁、钛等）与制法（锻造／铸造），偏置量与轮盘造型自由度大。
          </p>
        </div>

        <p className="image">
          <img alt="" src={i1QTArcWtOMm4} />
        </p>

        <h3>
          Three-Piece / 三片式
        </h3>

        <div className="bilingual">
          <p lang="en">
            A three-piece wheel is made from separate inner and outer rim sections, with the center disc attached using perimeter bolts. Like two-piece designs, it offers flexibility in materials and construction, along with a wide range of styling and offset options. The additional hardware can add weight, but it allows even greater design freedom, making this type popular for custom and high-end applications.
          </p>
          <p lang="zh">
            外侧与内侧轮辋焊接，轮盘再用周圈螺栓组装。具备两片式的特点与长处，（因周圈螺栓）重量略不利，但设计自由度最高，多用于重视造型的轮毂。
          </p>
        </div>

        <p className="image">
          <img alt="" src={i1dvybpzM9rPAuH} />
        </p>

        <h3 className="section-header">
          ● Manufacturing Methods / ● 制法
        </h3>

        <h3>
          Casting / 铸造
        </h3>

        <div className="bilingual">
          <p lang="en">
            Casting is a manufacturing method in which molten aluminum is poured into a mold. It allows a high degree of design flexibility, particularly for the wheel center. However, to achieve sufficient strength, the material often needs to be thicker, which can limit weight savings compared with steel wheels. Even so, its low cost makes casting the most common method for producing aluminum wheels.
          </p>
          <p lang="zh">
            将高温熔化的铝浇入铸模成型。两片式、三片式中轮盘造型自由度高是其优点；为取得足够强度往往需加厚壁厚，相对钢制的重量优势较小。成本低，含原厂件在内，是当今铝轮毂的主流。
          </p>
        </div>

        <h3>
          Forging / 锻造
        </h3>

        <div className="bilingual">
          <p lang="en">
            In forging, a block of metal is compressed under extremely high pressure, aligning its internal grain structure and producing a dense, strong material. Compared with casting, the material is stronger, allowing for thinner sections and reduced weight. The result is high strength and rigidity, along with improved resistance to fatigue. Forging is more expensive and offers less design flexibility than casting. While aluminum is most common, magnesium is also used in some racing and high-performance applications for further weight reduction.
          </p>
          <p lang="zh">
            以数千吨级高压压缩金属块，使之更韧、更硬。比铸造强度高，可减薄壁厚而轻量化。不过硬度高则抗拉强、抗弯相对弱，生产成本高，设计也易受限制。材料不限于铝；竞赛车与部分跑车会装比铝更轻的镁锻轮毂。
          </p>
        </div>
      </div>
    </div>
  </>
);

export default UnsprungWeight;
